// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Day03Scaffold.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Day03Scaffold.Context
{
    public partial interface IITIContextProcedures
    {
        Task<int> GetStudentIDByNameAsync(string sName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetStudentNameAndAgeByIDAsync(int? sid, OutputParameter<string> sName, OutputParameter<string> sAge, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ShowAllStudentsResult>> ShowAllStudentsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ShowStudentsFromCairoResult>> ShowStudentsFromCairoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<StudentByIDResult>> StudentByIDAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
