// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day03Scaffold.Entities;

[Keyless]
public partial class StudName
{
    public int St_Id { get; set; }

    [StringLength(50)]
    public string St_Fname { get; set; }
}